PUT http://localhost:8080/events/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzc1MDc0NjY4LCJ1c2VySWQiOjN9._y-mXBv9_DkzELHCI1uCj7juAPT1nBHNffUl7ycBJmQ

{
    "name": "Test event changed",
    "description": "A test event changed",
    "location": "A test location changed",
    "dateTime": "2026-02-13T23:14:34.000Z"
}